### ISSUE TITLE
Theme didn't take effect globally

### ISSUE THREAD

**Issue by LamFTS** [i-mint/bluesky#2]
Dear developer, It is of great honor to meet this beautiful theme, however, I found a bug of it, I install this theme by extract it into ~/.theme folder, and applied it using gnome-tweak-tool, but I notice that theme can be select in only Legacy Application, many in-build gnome application such as nautilus and calendar can't be rendered by this theme, while terminal and some other third-part application do. My environment detail:
OS: Archlinux 6.0.7-arch1-1
Desktop Environment: GNOME Shell 43.1
Application that didn't rendered by theme:
![Screenshot from 2022-11-09 20-05-36](https://user-images.githubusercontent.com/53118840/200826371-eca1ef24-aba6-4d24-aaf9-7c54b54cb52e.png)
Application that rendered by theme:
![image](https://user-images.githubusercontent.com/53118840/200826528-878ea262-0072-4b48-9c76-a90058fbe6b5.png)
Tweak-tool setting:
![image](https://user-images.githubusercontent.com/53118840/200826907-b02831a9-d1ad-4231-bf55-d0a9e2ce9ac2.png)
May this has something to do with GNOME?

**Comment by i-mint** [comment]
This theme does not yet support GTK-4.0 (Libadwaita), can only be used well in GTK-3.0

**Comment by LamFTS** [comment]
what a pity, thanks anyway.
