### ISSUE TITLE
[FIXED] Issue with renaming file in Nemo and List View mode

### ISSUE THREAD

**Issue by thegreatyellow67** [i-mint/bluesky#3]
Hi, please help me for your nice theme!

I'm using your BlueSky theme for a Linux Mint 21.3 Cinnamon YT tutorial and I've found an issue: when I try to rename a file in Nemo in List View, the name isn't highlighted and it's not possible to understand what exactly I'm trying to modifying in the name. See the simple gif attacched. How to solve? Thanks!

![Peek 23-03-2024 21-10](https://github.com/i-mint/bluesky/assets/41580754/e0916304-aeba-4154-a315-2986e87991c9)

**Comment by i-mint** [comment]
This issue has been fixed, in July to be exact. Thanks for the report!

**Comment by thegreatyellow67** [comment]
Thanks to you!!

**Comment by i-mint** [comment]
You're welcome!
